project:
  type: website

format:
  html:
    theme:
    - cosmo
    - collabora.scss 
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    logo: imgs/logo.svg
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]